# Generated by Django 5.2 on 2025-05-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_todoitem_created_at_todoitem_created_by_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='task',
            new_name='todo',
        ),
    ]
