# Generated by Django 5.2 on 2025-05-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_remove_comment_todo_comment_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roommates.room'),
        ),
    ]
