# Generated by Django 5.2 on 2025-05-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_alter_task_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roommates.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.room'),
        ),
    ]
