# Generated by Django 5.2 on 2025-05-08 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0005_alter_comment_task_alter_task_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='task',
            new_name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roommates.room'),
        ),
    ]
