# Generated by Django 5.2 on 2025-05-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0007_alter_comment_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tasks',
            new_name='task',
        ),
    ]
